CREATE TABLE "CCBADM"."LOGGING_STORE"
(	"ID" NUMBER(19,0),
   "CLIENT_APPLIKATION" VARCHAR2(30 CHAR),
   "CLIENT_VERSION" VARCHAR2(1024 CHAR),
   "CORRELATION_ID" VARCHAR2(64 CHAR),
   "DEBUG_INFORMATION" VARCHAR2(4000 CHAR),
   "FAULT_CODE" VARCHAR2(256 CHAR),
   "FAULT_MESSAGE" VARCHAR2(4000 CHAR),
   "FAULT_TYPE" VARCHAR2(64 CHAR),
   "SEVERITY" VARCHAR2(64 CHAR),
   "TIMESTAMP" TIMESTAMP (6)
)